// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/matching": {
    params: {};
  };
  "/upload": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/matching" | "/upload";
  };
  "./pages/Root.tsx": {
    id: "pages/Root";
    page: "/" | "/login" | "/matching" | "/upload";
  };
  "./pages/TerribleHome.tsx": {
    id: "pages/TerribleHome";
    page: "/";
  };
  "./pages/amplify-ui/AmplifyLogin.tsx": {
    id: "pages/amplify-ui/AmplifyLogin";
    page: "/login";
  };
  "./pages/Details.tsx": {
    id: "pages/Details";
    page: "/matching";
  };
  "./pages/Upload.tsx": {
    id: "pages/Upload";
    page: "/upload";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Root": typeof import("./src/./pages/Root.tsx");
  "pages/TerribleHome": typeof import("./src/./pages/TerribleHome.tsx");
  "pages/amplify-ui/AmplifyLogin": typeof import("./src/./pages/amplify-ui/AmplifyLogin.tsx");
  "pages/Details": typeof import("./src/./pages/Details.tsx");
  "pages/Upload": typeof import("./src/./pages/Upload.tsx");
};